package com.sunshine.core

// Generated by the fixture extraction script in investigations/dem-source-evaluation.md.
// Source: https://tiles.mapterhorn.com/12/{x}/{y}.webp, fetched 2026-09-26.
// The 2 x 2 samples (pixel centres) around each oracle point of the elevation-data spec.

/** One Terrarium sample: tile [x]/[y] at zoom 12, pixel [column]/[row], colour as opaque ARGB. */
internal data class FixtureSample(
    val x: Int,
    val y: Int,
    val column: Int,
    val row: Int,
    val argb: Int,
)

internal val ELEVATION_FIXTURE_SAMPLES: List<FixtureSample> =
    listOf(
        // INTERLAKEN
        FixtureSample(2137, 1445, 237, 454, 0xFF823800.toInt()),
        FixtureSample(2137, 1445, 238, 454, 0xFF823800.toInt()),
        FixtureSample(2137, 1445, 237, 455, 0xFF823800.toInt()),
        FixtureSample(2137, 1445, 238, 455, 0xFF823800.toInt()),
        // KLEINE_SCHEIDEGG
        FixtureSample(2138, 1447, 295, 287, 0xFF880D80.toInt()),
        FixtureSample(2138, 1447, 296, 287, 0xFF880D00.toInt()),
        FixtureSample(2138, 1447, 295, 288, 0xFF880D80.toInt()),
        FixtureSample(2138, 1447, 296, 288, 0xFF880D80.toInt()),
        // TILE_CORNER
        FixtureSample(2137, 1447, 511, 511, 0xFF846400.toInt()),
        FixtureSample(2138, 1447, 0, 511, 0xFF846E00.toInt()),
        FixtureSample(2137, 1448, 511, 0, 0xFF846A80.toInt()),
        FixtureSample(2138, 1448, 0, 0, 0xFF847400.toInt()),
        // JUNGFRAU
        FixtureSample(2138, 1448, 304, 186, 0xFF902E00.toInt()),
        FixtureSample(2138, 1448, 305, 186, 0xFF903680.toInt()),
        FixtureSample(2138, 1448, 304, 187, 0xFF903600.toInt()),
        FixtureSample(2138, 1448, 305, 187, 0xFF903A80.toInt()),
    )
